In [1]:
import numpy as np

In [2]:
# 일반적인 list 생성
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [43]:
# numpy array 생성
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [5]:
# array 크기 확인
arr1.shape

(5,)

In [39]:
# numpy array 생성2
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [8]:
# array의 자료형을 확인
arr2.dtype

dtype('int32')

In [9]:
# 2차 array
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
arr3.shape

(4, 3)

In [25]:
# 2차원 : np.zeros((3,5))
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
# 2차원 : np.ones((2,10))
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# 3씩 증가하는 arange
np.arange(100,125,3)

array([100, 103, 106, 109, 112, 115, 118, 121, 124])

In [26]:
arr1 + arr2

array([ 2,  4,  6,  8, 10])

In [27]:
arr1 - arr2

array([0, 0, 0, 0, 0])

In [28]:
arr1 * arr2

array([ 1,  4,  9, 16, 25])

In [40]:
arr1 / arr2

array([1., 1., 1., 1., 1.])

In [48]:
data = np.random.randn(8,4)
data

array([[ 1.50931817,  0.16787865,  0.8103822 , -1.8856432 ],
       [-0.60822071, -1.29050751,  0.85874346, -0.15889133],
       [-1.30252198,  0.82837281, -1.18352045,  1.64007962],
       [-0.23658807,  1.98370288,  0.56439089,  0.9778745 ],
       [-0.27873364, -0.38589087,  0.56084095, -0.62610039],
       [-0.02758789,  2.0705399 ,  0.38396584, -0.13343927],
       [ 0.45184295,  2.24408338, -0.45536117, -0.54595311],
       [ 0.25092057, -0.93075793, -1.47439869, -0.26367868]])

In [51]:
data = np.random.rand(8,4)
data

array([[0.62219377, 0.6563605 , 0.11321861, 0.69094802],
       [0.77107066, 0.52744531, 0.32833976, 0.97361258],
       [0.08308554, 0.35511555, 0.58424147, 0.35955998],
       [0.03943267, 0.30236616, 0.20090291, 0.85539552],
       [0.99643802, 0.54485383, 0.71381079, 0.37128933],
       [0.33612347, 0.4538166 , 0.05481138, 0.56000609],
       [0.25356157, 0.84264847, 0.20441865, 0.42690154],
       [0.51861562, 0.12087852, 0.72319198, 0.70026275]])

In [52]:
arr3 = arr3.T
arr3

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [53]:
arr3 = arr3.T
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
arr4 = arr3.reshape(12)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
arr4 = arr3.reshape(3,4)
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
arr5 = np.square(data)
arr5

array([[0.38712508, 0.43080911, 0.01281845, 0.47740917],
       [0.59454996, 0.27819855, 0.107807  , 0.94792145],
       [0.00690321, 0.12610706, 0.3413381 , 0.12928338],
       [0.00155494, 0.0914253 , 0.04036198, 0.73170149],
       [0.99288872, 0.2968657 , 0.50952585, 0.13785577],
       [0.11297899, 0.2059495 , 0.00300429, 0.31360683],
       [0.06429347, 0.71005645, 0.04178698, 0.18224492],
       [0.26896216, 0.01461162, 0.52300664, 0.49036792]])